services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333

  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_data:/data
    environment:
      NEO4J_AUTH: neo4j/reform-william-center-vibrate-press-5829
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,apoc.meta.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,apoc.meta.*'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'

  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: graphlm
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j_data:
  postgres_data: